import { chromium, expect } from '@playwright/test'
import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { dismissEntryGuide } from './entry-guide.mjs'

const url = process.env.TEST_URL || 'http://127.0.0.1:5188/'
const candidate = process.env.BROWSER_EXECUTABLE || chromium.executablePath()
const options = { headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] }
if (existsSync(candidate)) options.executablePath = candidate
else if (existsSync('C:/Program Files/Google/Chrome/Application/chrome.exe')) options.executablePath = 'C:/Program Files/Google/Chrome/Application/chrome.exe'
const browser = await chromium.launch(options)
const page = await browser.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 1 })
const errors = []
const checks = []
page.on('pageerror', (error) => errors.push(error.message))
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
const output = path.resolve(process.env.TEST_OUTPUT_DIR || '..')
await mkdir(output, { recursive: true })
try {
  await page.goto(url, { waitUntil: 'networkidle' })
  await page.locator('.scene-loading').waitFor({ state: 'detached', timeout: 45000 })
  await page.locator('canvas').waitFor({ state: 'visible' })
  await dismissEntryGuide(page)
  assert.equal(await page.locator('.planet-caption').count(), 10)
  assert.equal(await page.locator('.star-caption strong').textContent(), "DON'T TAP THE GLASS")
  const dimensions = await page.locator('[data-testid="galaxy-viewport"]').boundingBox()
  assert.deepEqual(dimensions, { x: 0, y: 0, width: 1600, height: 900 })
  assert.equal(await page.locator('canvas').getAttribute('data-projection'), 'perspective')
  assert.equal(await page.evaluate(() => document.documentElement.scrollHeight > innerHeight), false)
  checks.push('Full-window perspective WebGL scene, album star and ten ordered planets render without page scroll')
  await page.getByRole('button', { name: '暂停动画', exact: true }).click()
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: path.join(output, 'music-universe-fullscreen.png'), fullPage: true })
  await page.locator('[data-testid="galaxy-viewport"]').screenshot({ path: path.join(output, 'music-universe-fullscreen-scene.png') })
  console.log('Initial render captured. Browser errors:', JSON.stringify(errors))
  // Canvas framing and GPU rendering may finish after the full-page capture.
  // Require identical frozen frames, allowing the asynchronous render to settle.
  let pausedA
  await expect.poll(async () => {
    pausedA = await page.locator('[data-testid="galaxy-viewport"]').screenshot()
    await page.waitForTimeout(150)
    const pausedB = await page.locator('[data-testid="galaxy-viewport"]').screenshot()
    return Buffer.compare(pausedA, pausedB)
  }, { timeout: 10000 }).toBe(0)
  await page.getByRole('button', { name: '继续动画', exact: true }).click()
  await page.waitForTimeout(700)
  const moving = await page.locator('[data-testid="galaxy-viewport"]').screenshot()
  assert.notEqual(Buffer.compare(pausedA, moving), 0)
  await page.getByRole('button', { name: '暂停动画', exact: true }).click()
  checks.push('Animation advances and pause freezes the rendered frame')

  await page.getByRole('button', { name: '曲目索引', exact: true }).click()
  await page.getByRole('button', { name: '查看 Sugar on My Tongue', exact: true }).click()
  assert.match(await page.locator('.planet-detail').innerText(), /Sugar on My Tongue/)
  await page.getByRole('button', { name: '关闭星球详情', exact: true }).click()
  await page.getByRole('button', { name: '曲目索引', exact: true }).click()
  await page.getByRole('button', { name: '查看 Sugar on My Tongue', exact: true }).click()
  await expect.poll(() => page.locator('canvas').getAttribute('data-camera-moving'), { timeout: 10000 }).toBe('false')
  await page.getByRole('button', { name: '下一颗歌曲星球', exact: true }).click()
  await expect(page.locator('.planet-detail strong')).toHaveText('Sucka Free')
  await expect.poll(() => page.locator('canvas').getAttribute('data-camera-moving'), { timeout: 10000 }).toBe('false')
  await page.getByRole('button', { name: '上一颗歌曲星球', exact: true }).click()
  await expect(page.locator('.planet-detail strong')).toHaveText('Sugar on My Tongue')
  await page.getByRole('button', { name: '关闭星球详情', exact: true }).click()
  checks.push('Expandable track drawer, track selection and previous / next navigation')
  await page.getByRole('button', { name: '重置视角', exact: true }).click()
  await expect(page.locator('.planet-caption')).toHaveCount(10)
  await page.getByRole('button', { name: '标签', exact: true }).click()
  assert.equal(await page.locator('.planet-caption').count(), 0)
  await page.getByRole('button', { name: '标签', exact: true }).click()
  assert.equal(await page.locator('.planet-caption').count(), 10)
  checks.push('Label visibility toggle')
  const canvasBounds = await page.locator('canvas').boundingBox()
  // Pick a sphere directly in 3D, then verify a strong camera gesture stays ordered.

  async function exportData() {
    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('button', { name: '导出星系 JSON', exact: true }).click()
    const download = await downloadPromise
    return JSON.parse(await readFile(await download.path(), 'utf8'))
  }
  await page.getByRole('textbox', { name: '星系 Seed', exact: true }).fill('QA-REPRODUCIBLE')
  await page.getByRole('button', { name: '重新生成', exact: true }).click()
  const first = await exportData()
  const firstPlanet = first.galaxy.planets[0]
  await page.locator('.scene-loading').waitFor({ state: 'detached' })
  await page.waitForTimeout(250)
  const center = await page.locator('.planet-number').first().evaluate((element) => ({ x: Number(element.dataset.centerX), y: Number(element.dataset.centerY) }))
  assert.ok(Number.isFinite(center.x) && Number.isFinite(center.y))
  await page.mouse.click(canvasBounds.x + center.x, canvasBounds.y + center.y)
  await expect(page.locator('.planet-detail strong')).toHaveText(firstPlanet.title)
  await page.getByRole('button', { name: '关闭星球详情', exact: true }).click()
  await expect(page.locator('canvas')).toHaveAttribute('data-view-mode', 'continuous')
  await expect.poll(() => page.locator('canvas').getAttribute('data-camera-moving'), { timeout: 10000 }).toBe('false')
  const focused = await page.locator('canvas').evaluate((element) => JSON.parse(element.dataset.projectedTargets).find((node) => node.id === element.dataset.focusTarget))
  await page.mouse.move(focused.x, focused.y)
  await page.mouse.down()
  await page.mouse.move(focused.x + 160, focused.y + 30, { steps: 10 })
  await page.mouse.up()
  assert.ok(Number(await page.locator('canvas').getAttribute('data-surface-yaw')) > 0.5)
  await page.getByRole('button', { name: '重置视角', exact: true }).click()
  await expect(page.locator('.planet-number')).toHaveCount(10)
  await expect.poll(() => page.locator('canvas').getAttribute('data-camera-moving'), { timeout: 10000 }).toBe('false')
  assert.deepEqual(await page.locator('.planet-number').allTextContents(), Array.from({ length: 10 }, (_, i) => String(i + 1).padStart(2, '0')))
  checks.push('Direct 3D picking and surface dragging work on orbital planets; reset preserves track identity and order in the index')
  await page.getByRole('button', { name: '重新生成', exact: true }).click()
  const second = await exportData()
  assert.deepEqual(first, second)
  await page.getByRole('button', { name: '随机生成', exact: true }).click()
  const randomized = await exportData()
  assert.notEqual(randomized.galaxy.seed, first.galaxy.seed)
  assert.notDeepEqual(randomized.galaxy.planets, first.galaxy.planets)
  assert.deepEqual(randomized.galaxy.planets.map((p) => p.title), first.galaxy.planets.map((p) => p.title))
  checks.push('Seed regeneration, reproducibility, random generation and JSON export')
  const beforeQuality = await exportData()
  await page.getByRole('button', { name: '画面品质', exact: true }).click()
  await page.getByRole('button', { name: '流畅', exact: true }).click()
  await expect.poll(async () => Number(await page.locator('canvas').getAttribute('data-render-dpr'))).toBeLessThan(1)
  const lowWidth = await page.locator('canvas').evaluate((element) => element.width)
  await page.getByRole('button', { name: '画面品质', exact: true }).click()
  await page.getByRole('button', { name: '精致', exact: true }).click()
  await expect.poll(() => page.locator('canvas').evaluate((element) => element.width)).toBeGreaterThan(lowWidth)
  assert.deepEqual(await exportData(), beforeQuality)
  await page.getByRole('button', { name: '画面品质', exact: true }).click()
  await page.getByRole('button', { name: '自适应', exact: true }).click()
  checks.push('Quality settings change actual canvas resolution without changing the seeded galaxy')
  await page.getByRole('button', { name: '沉浸模式', exact: true }).click()
  await expect(page.locator('.universe-hud')).toHaveAttribute('inert', '')
  await expect(page.locator('.scene-label-layer')).toHaveCount(0)
  await page.screenshot({ path: path.join(output, 'music-universe-immersive.png') })
  await page.getByRole('button', { name: '显示界面', exact: true }).click()
  await page.keyboard.press('h')
  await expect(page.getByRole('button', { name: '显示界面', exact: true })).toBeVisible()
  await page.keyboard.press('h')
  await expect(page.getByRole('button', { name: '显示界面', exact: true })).toHaveCount(0)
  await expect(page.locator('.universe-hud')).not.toHaveAttribute('inert', '')
  checks.push('Immersive mode hides controls and labels, disables hidden focus, and restores with button or H')

  await page.getByRole('button', { name: '编辑专辑', exact: true }).click()
  await page.getByLabel('专辑名称', { exact: true }).fill('QA TEST ALBUM')
  await page.getByLabel('歌手 / 艺术家', { exact: true }).fill('Test Artist')
  await page.getByRole('textbox', { name: '曲目列表', exact: true }).fill('First | 3:02\nSecond | 2:40\nThird | 4:01')
  await page.getByLabel('上传专辑封面', { exact: true }).setInputFiles(path.resolve('public/covers/dont-tap-the-glass.jpg'))
  await page.locator('.cover-success').waitFor()
  await page.getByRole('button', { name: '保存并生成', exact: true }).click()
  assert.equal(await page.locator('h1').textContent(), 'QA TEST ALBUM')
  await expect(page.locator('.planet-caption')).toHaveCount(3)
  const edited = await exportData()
  assert.equal(edited.album.artist, 'Test Artist')
  assert.ok(edited.album.cover.startsWith('data:image/jpeg'))
  assert.deepEqual(edited.galaxy.planets.map((p) => p.title), ['First', 'Second', 'Third'])
  checks.push('Album metadata, ordered track editing and local cover upload')

  await page.getByRole('button', { name: '编辑专辑', exact: true }).click()
  await page.getByRole('textbox', { name: '曲目列表', exact: true }).fill('Bad | 3:99')
  await page.getByRole('button', { name: '保存并生成', exact: true }).click()
  assert.match(await page.getByRole('alert').innerText(), /时长/)
  await page.getByRole('button', { name: '恢复示例', exact: true }).click()
  await page.locator('#cover-url').fill(`${url}covers/dont-tap-the-glass.jpg`)
  await page.getByRole('button', { name: '载入封面 URL', exact: true }).click()
  await page.locator('.cover-success').waitFor()
  await page.getByRole('button', { name: '保存并生成', exact: true }).click()
  await expect(page.locator('.planet-caption')).toHaveCount(10)
  checks.push('Validation errors, restore example and cover URL input')

  await page.getByRole('button', { name: '使用指南', exact: true }).click()
  await page.locator('.guide-dialog').waitFor({ state: 'visible' })
  await page.getByRole('button', { name: '开始遨游', exact: true }).click()
  await page.getByRole('button', { name: '重置视角', exact: true }).click()
  checks.push('Guide dialog and camera reset')
  await page.getByRole('button', { name: '全屏查看星系', exact: true }).click()
  await expect.poll(() => page.evaluate(() => Boolean(document.fullscreenElement))).toBe(true)
  await page.getByRole('button', { name: '全屏查看星系', exact: true }).click()
  await expect.poll(() => page.evaluate(() => Boolean(document.fullscreenElement))).toBe(false)
  checks.push('Browser fullscreen enters and exits with the entire scene and controls')
  await page.getByRole('button', { name: '编辑专辑', exact: true }).click()
  await page.getByRole('textbox', { name: '曲目列表', exact: true }).fill(Array.from({ length: 17 }, (_, i) => `Long album track ${String(i + 1).padStart(2, '0')}`).join('\n'))
  await page.getByRole('button', { name: '保存并生成', exact: true }).click()
  await expect(page.locator('.planet-caption')).toHaveCount(17)
  await expect.poll(async () => {
    const centers = await page.locator('.planet-number').evaluateAll((elements) => elements.map(element => [+element.dataset.centerX, +element.dataset.centerY]))
    const targets = await page.locator('canvas').evaluate(element => JSON.parse(element.dataset.projectedTargets).slice(1))
    return centers.length === targets.length && centers.every((center, index) => Math.hypot(center[0] - targets[index].x, center[1] - targets[index].y) < 0.05)
  }).toBe(true)
  checks.push('Seventeen-track album keeps every label attached to its planet and preserves track identity')
  await page.getByRole('button', { name: '编辑专辑', exact: true }).click()
  await page.getByRole('button', { name: '恢复示例', exact: true }).click()
  await page.getByRole('button', { name: '保存并生成', exact: true }).click()
  await expect(page.locator('.planet-caption')).toHaveCount(10)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.join(output, 'music-universe-fullscreen-mobile.png'), fullPage: true })
  const mobileDimensions = await page.locator('[data-testid="galaxy-viewport"]').boundingBox()
  assert.deepEqual(mobileDimensions, { x: 0, y: 0, width: 390, height: 844 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  assert.equal(await page.evaluate(() => document.documentElement.scrollHeight > innerHeight), false)
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    const viewport = await page.locator('.galaxy-viewport').boundingBox()
    const controls = await page.locator('.control-bar').boundingBox()
    const header = await page.locator('.site-header').boundingBox()
    const fullButton = await page.getByRole('button', { name: '全屏查看星系', exact: true }).boundingBox()
    assert.deepEqual(viewport, { x: 0, y: 0, width, height: 844 })
    assert.ok(controls.x >= 0 && controls.x + controls.width <= width)
    assert.ok(fullButton.x + fullButton.width <= header.x + header.width + 1)
    await page.getByRole('button', { name: '曲目索引', exact: true }).click()
    const drawer = await page.locator('.track-index').boundingBox()
    assert.ok(drawer.x >= 0 && drawer.x + drawer.width <= width)
    await page.getByRole('button', { name: '收起曲目索引', exact: true }).click()
  }
  await page.setViewportSize({ width: 844, height: 390 })
  const landscape = await page.locator('.galaxy-viewport').boundingBox()
  assert.deepEqual(landscape, { x: 0, y: 0, width: 844, height: 390 })
  assert.deepEqual(await page.locator('.planet-number').allTextContents(), Array.from({ length: 10 }, (_, i) => String(i + 1).padStart(2, '0')))
  checks.push('390 / 320 portrait and phone landscape fill the window, keep controls inside and preserve track order')
  assert.deepEqual(errors, [])
  await writeFile(path.join(output, 'music-universe-browser-report.json'), JSON.stringify({ url, checks, errors, passed: true }, null, 2))
  console.log(JSON.stringify({ passed: true, checks, errors }, null, 2))
} catch (error) {
  await page.screenshot({ path: path.join(output, 'music-universe-test-failure.png'), fullPage: true }).catch(() => {})
  await writeFile(path.join(output, 'music-universe-browser-report.json'), JSON.stringify({ url, checks, errors, passed: false, failure: String(error) }, null, 2))
  throw error
} finally { await browser.close() }
