import { chromium, expect } from '@playwright/test'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
const output = process.env.TEST_OUTPUT_DIR || 'tests/reports/universe-polish'; mkdirSync(output, { recursive: true })
const origin = process.env.TEST_HALL_ORIGIN || 'http://127.0.0.1:3002'
const executablePath = existsSync(chromium.executablePath()) ? chromium.executablePath() : 'C:/Program Files/Google/Chrome/Application/chrome.exe'
const browser = await chromium.launch({ executablePath, headless: true, ignoreDefaultArgs: ['--mute-audio'], args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
const page = await context.newPage(), errors = [], checks = [], failures = []
page.on('pageerror', error => errors.push(error.message))
page.on('console', message => { if (message.type() === 'error' && !message.text().includes('favicon.ico')) errors.push(message.text()) })
page.on('response', response => { if (response.status() >= 400) failures.push({ status: response.status(), path: new URL(response.url()).pathname }) })
try {
  await page.goto(origin + '/#hall', { waitUntil: 'domcontentloaded' })
  const portal = page.getByTestId('hall-universe-entry')
  await expect(portal).toHaveAttribute('href', '/#universe')
  await portal.click()
  await expect(page.locator('.mw-universe-transition')).toBeVisible()
  expect((await page.locator('.mw-universe-transition').innerText()).trim()).toBe('')
  await expect(page).toHaveURL(/#universe$/)
  const frame = page.frameLocator('.mw-universe-room iframe')
  await expect(frame.locator('canvas')).toHaveAttribute('data-frame-count', /\d+/, { timeout: 60000 })
  await expect(page.locator('.mw-universe-room')).toHaveClass(/is-ready/, { timeout: 45000 })
  await expect(page.locator('.mw-fog-transition')).toHaveCount(0, { timeout: 15000 })
  expect((await page.locator('.mw-universe-loading').innerText()).trim()).toBe('')
  const dimensions = await frame.getByTestId('galaxy-viewport').boundingBox()
  expect(dimensions).toEqual({ x: 0, y: 0, width: 1440, height: 900 })
  const guide = frame.getByRole('button', { name: '开始遨游', exact: true })
  if (await guide.isVisible()) await guide.click()
  await expect(frame.locator('.app-shell')).toHaveAttribute('data-album-cover', '/universe/covers/dont-tap-the-glass.jpg')
  await page.screenshot({ path: output + '/merged-desktop.png' })
  checks.push('Same-origin hall → universe; animation-only transition/loading; full-screen 3D; cover/font/background resources')
  await frame.getByRole('button', { name: '沉浸模式', exact: true }).click()
  const shell = frame.locator('.app-shell'), handle = frame.locator('.immersive-player-handle')
  await expect(shell).toHaveClass(/hud-hidden/)
  await page.mouse.move(700, 890)
  await page.waitForTimeout(120)
  expect((await shell.getAttribute('class')).includes('player-revealed')).toBe(false)
  await page.mouse.move(700, 550)
  await page.waitForTimeout(400)
  expect((await shell.getAttribute('class')).includes('player-revealed')).toBe(false)
  await page.mouse.move(700, 890)
  await expect(shell).toHaveClass(/player-revealed/, { timeout: 2500 })
  await page.mouse.move(700, 490)
  await page.waitForTimeout(250)
  await expect(shell).toHaveClass(/player-revealed/)
  await expect.poll(async () => (await shell.getAttribute('class')).includes('player-revealed'), { timeout: 3000 }).toBe(false)
  await handle.click()
  await frame.getByRole('button', { name: '播放队列', exact: true }).click()
  await page.mouse.move(100, 250)
  await page.waitForTimeout(1400)
  await expect(shell).toHaveClass(/player-revealed/)
  await frame.getByRole('button', { name: '收起播放队列', exact: true }).click()
  await frame.getByRole('button', { name: '关闭底部播放器', exact: true }).click()
  expect((await shell.getAttribute('class')).includes('player-revealed')).toBe(false)
  await page.screenshot({ path: output + '/immersive.png' })
  checks.push('Hover dwell/cancel; delayed close; queue holds popup; manual close')
  // Ignore messages from the top document instead of the expected iframe.
  await page.evaluate(() => window.postMessage({ type: 'music-universe:navigate', room: 'hall' }, location.origin))
  await page.waitForTimeout(300)
  await expect(page).toHaveURL(/#universe$/)
  await frame.getByRole('button', { name: '显示界面', exact: true }).click()
  // A generated, untagged WAV exercises the real decoder/output without
  // depending on third-party rights, metadata services, or an invented song.
  const sampleRate = 22050, samples = sampleRate * 20, wav = Buffer.alloc(44 + samples * 2)
  wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8)
  wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22)
  wav.writeUInt32LE(sampleRate, 24); wav.writeUInt32LE(sampleRate * 2, 28)
  wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(samples * 2, 40)
  for (let i = 0; i < samples; i++) wav.writeInt16LE(Math.round(2500 * Math.sin(i / sampleRate * Math.PI * 2 * 440)), 44 + i * 2)
  await frame.getByRole('button', { name: '音乐搜索', exact: true }).click()
  await frame.getByTestId('music-search-file').setInputFiles({ name: 'local-output-check.wav', mimeType: 'audio/wav', buffer: wav })
  const audio = frame.getByTestId('audio-engine')
  await expect.poll(() => audio.evaluate(a => !a.paused && !a.muted && a.volume > 0 && a.currentTime > .15 && !a.error), { timeout: 15000 }).toBe(true)
  await audio.evaluate(async a => {
    const context = new AudioContext(), analyser = context.createAnalyser()
    context.createMediaElementSource(a).connect(analyser); analyser.connect(context.destination)
    await context.resume(); window.localOutputProbe = { context, analyser }
  })
  await expect.poll(() => audio.evaluate(() => {
    const analyser = window.localOutputProbe.analyser, data = new Float32Array(analyser.fftSize)
    analyser.getFloatTimeDomainData(data)
    return Math.sqrt(data.reduce((sum, v) => sum + v * v, 0) / data.length)
  }), { timeout: 10000 }).toBeGreaterThan(.01)
  await audio.evaluate(async a => { a.pause(); await window.localOutputProbe.context.close() })
  await frame.getByRole('button', { name: '关闭音乐搜索', exact: true }).click()
  checks.push('Merged subpage local WAV: native playback, unmuted volume, decoded PCM reaching output destination')
  await frame.locator('.site-header a[href$="#hall"]').click()
  await expect(page).toHaveURL(/#hall$/, { timeout: 12000 })
  await expect(portal).toBeVisible({ timeout: 15000 })
  checks.push('Return animated to hall; message source/origin isolation')
  const response = await context.request.get(origin + '/universe/index.html')
  expect(response.status()).toBe(200)
  expect(response.headers()['x-frame-options']).toBe('SAMEORIGIN')
  expect(response.headers()['content-security-policy']).toContain("frame-ancestors 'self'")
  const hallResponse = await context.request.get(origin + '/')
  expect(hallResponse.headers()['x-frame-options']).toBe('DENY')
  expect(hallResponse.headers()['content-security-policy']).toContain("'strict-dynamic'")
  checks.push('Only universe subpage allows same-origin embedding; main CSP stays strict')
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 })
  const m = await mobile.newPage()
  m.on('pageerror', error => errors.push(error.message))
  await m.goto(origin + '/#universe')
  const mf = m.frameLocator('.mw-universe-room iframe')
  await expect(mf.locator('canvas')).toHaveAttribute('data-frame-count', /\d+/, { timeout: 60000 })
  await expect(m.locator('.mw-universe-room')).toHaveClass(/is-ready/, { timeout: 60000 })
  if (await mf.getByRole('button', { name: '开始遨游', exact: true }).isVisible()) await mf.getByRole('button', { name: '开始遨游', exact: true }).tap()
  await mf.getByRole('button', { name: '沉浸模式', exact: true }).tap()
  const mh = mf.locator('.immersive-player-handle')
  await mh.tap(); await expect(mf.locator('.app-shell')).toHaveClass(/player-revealed/)
  await mf.getByRole('button', { name: '关闭底部播放器', exact: true }).tap()
  const box = await mh.boundingBox(), session = await mobile.newCDPSession(m)
  const x = box.x + box.width / 2, y = box.y + box.height / 2
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y: y - 85 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(mf.locator('.app-shell')).toHaveClass(/player-revealed/)
  await expect(mf.getByRole('button', { name: '关闭底部播放器', exact: true })).toBeVisible()
  await expect.poll(() => mf.locator('.player-shell').evaluate(element => getComputedStyle(element).opacity)).toBe('1')
  await m.waitForTimeout(500)
  await m.screenshot({ path: output + '/mobile-player.png' })
  checks.push('Mobile tap and actual touch swipe open; manual close; 390px viewport')
  await mobile.close()
  expect(failures).toEqual([])
  expect(errors).toEqual([])
  writeFileSync(output + '/results.json', JSON.stringify({ passed: true, checks, errors, failures }, null, 2))
  console.log(JSON.stringify({ passed: true, checks }, null, 2))
} catch (error) {
  await page.screenshot({ path: output + '/failure.png' }).catch(() => {})
  writeFileSync(output + '/results.json', JSON.stringify({ passed: false, checks, errors, failures, error: String(error) }, null, 2))
  throw error
} finally { await browser.close() }
